saleor/saleor/demo/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from ..graphql.api import schema
from ..urls import urlpatterns as core_urlpatterns
from .views import DemoGraphQLView

urlpatterns = [
    path("graphql/", csrf_exempt(DemoGraphQLView.as_view(schema=schema)), name="api"),
]

urlpatterns += core_urlpatterns

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt

from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .plugins.views import handle_plugin_webhook
from .product.views import digital_product

urlpatterns = [
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        digital_product,
        name="digital-product",
    ),
    url(
        r"plugins/(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_plugin_webhook,
        name="plugins",
    ),
]

if settings.DEBUG:
    import warnings
    from .core import views

    try:
        import debug_toolbar
    except ImportError:
        warnings.warn(
            "The debug toolbar was not installed. Ignore the error. \
            settings.py should already have warned the user about it."
        )
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT) + [
        url(r"^static/(?P<path>.*)$", serve),
        url(r"^", views.home, name="home"),
    ]

saleor/saleor/invoice/models.py
from django.conf import settings
from django.db import models
from django.db.models import JSONField  # type: ignore
from django.utils.timezone import now

from ..core import JobStatus
from ..core.models import Job, ModelWithMetadata
from ..core.utils import build_absolute_uri
from ..core.utils.json_serializer import CustomJsonEncoder
from ..order.models import Order
from . import InvoiceEvents


class InvoiceQueryset(models.QuerySet):
    def ready(self):
        return self.filter(job__status=JobStatus.SUCCESS)


class Invoice(ModelWithMetadata, Job):
    order = models.ForeignKey(
        Order, related_name="invoices", null=True, on_delete=models.SET_NULL
    )
    number = models.CharField(max_length=255, null=True)
    created = models.DateTimeField(null=True)
    external_url = models.URLField(null=True, max_length=2048)
    invoice_file = models.FileField(upload_to="invoices")
    objects = InvoiceQueryset.as_manager()

    @property
    def url(self):
        if self.invoice_file:
            return build_absolute_uri(self.invoice_file.url)
        return self.external_url

    @url.setter
    def url(self, value):
        self.external_url = value

    def update_invoice(self, number=None, url=None):
        if number is not None:
            self.number = number
        if url is not None:
            self.external_url = url


class InvoiceEvent(models.Model):
    """Model used to store events that happened during the invoice lifecycle."""

    date = models.DateTimeField(default=now, editable=False)
    type = models.CharField(max_length=255, choices=InvoiceEvents.CHOICES)
    invoice = models.ForeignKey(
        Invoice, related_name="events", blank=True, null=True, on_delete=models.SET_NULL
    )
    order = models.ForeignKey(
        Order,
        related_name="invoice_events",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    parameters = JSONField(blank=True, default=dict, encoder=CustomJsonEncoder)

    class Meta:
        ordering = ("date", "pk")

    def __repr__(self):
        return f"{self.__class__.__name__}(type={self.type!r}, user={self.user!r})"

saleor/saleor/product/models.py
import datetime
from typing import TYPE_CHECKING, Iterable, Optional, Union
from uuid import uuid4

from django.conf import settings
from django.contrib.postgres.aggregates import StringAgg
from django.db import models
from django.db.models import JSONField  # type: ignore
from django.db.models import Case, Count, F, FilteredRelation, Q, Sum, Value, When
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.utils.encoding import smart_text
from django_measurement.models import MeasurementField
from django_prices.models import MoneyField
from draftjs_sanitizer import clean_draft_js
from measurement.measures import Weight
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from versatileimagefield.fields import PPOIField, VersatileImageField

from ..core.db.fields import SanitizedJSONField
from ..core.models import (
    ModelWithMetadata,
    PublishableModel,
    PublishedQuerySet,
    SortableModel,
)
from ..core.permissions import ProductPermissions, ProductTypePermissions
from ..core.utils import build_absolute_uri
from ..core.utils.draftjs import json_content_to_raw_text
from ..core.utils.translations import TranslationProxy
from ..core.weight import WeightUnits, zero_weight
from ..discount import DiscountInfo
from ..discount.utils import calculate_discounted_price
from ..seo.models import SeoModel, SeoModelTranslation
from . import AttributeInputType

if TYPE_CHECKING:
    # flake8: noqa
    from prices import Money

    from ..account.models import User
    from django.db.models import OrderBy


class Category(MPTTModel, ModelWithMetadata, SeoModel):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    description = models.TextField(blank=True)
    description_json = JSONField(blank=True, default=dict)
    parent = models.ForeignKey(
        "self", null=True, blank=True, related_name="children", on_delete=models.CASCADE
    )
    background_image = VersatileImageField(
        upload_to="category-backgrounds", blank=True, null=True
    )
    background_image_alt = models.CharField(max_length=128, blank=True)

    objects = models.Manager()
    tree = TreeManager()
    translated = TranslationProxy()

    def __str__(self) -> str:
        return self.name


class CategoryTranslation(SeoModelTranslation):
    language_code = models.CharField(max_length=10)
    category = models.ForeignKey(
        Category, related_name="translations", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    description_json = JSONField(blank=True, default=dict)

    class Meta:
        unique_together = (("language_code", "category"),)

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        class_ = type(self)
        return "%s(pk=%r, name=%r, category_pk=%r)" % (
            class_.__name__,
            self.pk,
            self.name,
            self.category_id,
        )


class ProductType(ModelWithMetadata):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    has_variants = models.BooleanField(default=True)
    is_shipping_required = models.BooleanField(default=True)
    is_digital = models.BooleanField(default=False)
    weight = MeasurementField(
        measurement=Weight, unit_choices=WeightUnits.CHOICES, default=zero_weight
    )

    class Meta:
        ordering = ("slug",)
        app_label = "product"
        permissions = (
            (
                ProductTypePermissions.MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES.codename,
                "Manage product types and attributes.",
            ),
        )

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        class_ = type(self)
        return "<%s.%s(pk=%r, name=%r)>" % (
            class_.__module__,
            class_.__name__,
            self.pk,
            self.name,
        )


class ProductsQueryset(PublishedQuerySet):
    def collection_sorted(self, user: "User"):
        qs = self.visible_to_user(user)
        qs = qs.order_by(
            F("collectionproduct__sort_order").asc(nulls_last=True),
            F("collectionproduct__id"),
        )
        return qs

    def published_with_variants(self):
        published = self.published()
        return published.filter(variants__isnull=False).distinct()

    def visible_to_user(self, user):
        if self.user_has_access_to_all(user):
            return self.all()
        return self.published_with_variants()

    def sort_by_attribute(
        self, attribute_pk: Union[int, str], descending: bool = False
    ):
        """Sort a query set by the values of the given product attribute.

        :param attribute_pk: The database ID (must be a numeric) of the attribute
                             to sort by.
        :param descending: The sorting direction.
        """
        qs: models.QuerySet = self
        # If the passed attribute ID is valid, execute the sorting
        if not (isinstance(attribute_pk, int) or attribute_pk.isnumeric()):
            return qs.annotate(
                concatenated_values_order=Value(
                    None, output_field=models.IntegerField()
                ),
                concatenated_values=Value(None, output_field=models.CharField()),
            )

        # Retrieve all the products' attribute data IDs (assignments) and
        # product types that have the given attribute associated to them
        associated_values = tuple(
            AttributeProduct.objects.filter(attribute_id=attribute_pk).values_list(
                "pk", "product_type_id"
            )
        )

        if not associated_values:
            qs = qs.annotate(
                concatenated_values_order=Value(
                    None, output_field=models.IntegerField()
                ),
                concatenated_values=Value(None, output_field=models.CharField()),
            )

        else:
            attribute_associations, product_types_associated_to_attribute = zip(
                *associated_values
            )

            qs = qs.annotate(
                # Contains to retrieve the attribute data (singular) of each product
                # Refer to `AttributeProduct`.
                filtered_attribute=FilteredRelation(
                    relation_name="attributes",
                    condition=Q(attributes__assignment_id__in=attribute_associations),
                ),
                # Implicit `GROUP BY` required for the `StringAgg` aggregation
                grouped_ids=Count("id"),
                # String aggregation of the attribute's values to efficiently sort them
                concatenated_values=Case(
                    # If the product has no association data but has
                    # the given attribute associated to its product type,
                    # then consider the concatenated values as empty (non-null).
                    When(
                        Q(product_type_id__in=product_types_associated_to_attribute)
                        & Q(filtered_attribute=None),
                        then=models.Value(""),
                    ),
                    default=StringAgg(
                        F("filtered_attribute__values__name"),
                        delimiter=",",
                        ordering=(
                            [
                                f"filtered_attribute__values__{field_name}"
                                for field_name in AttributeValue._meta.ordering or []
                            ]
                        ),
                    ),
                    output_field=models.CharField(),
                ),
                concatenated_values_order=Case(
                    # Make the products having no such attribute be last in the sorting
                    When(concatenated_values=None, then=2),
                    # Put the products having an empty attribute value at the bottom of
                    # the other products.
                    When(concatenated_values="", then=1),
                    # Put the products having an attribute value to be always at the top
                    default=0,
                    output_field=models.IntegerField(),
                ),
            )

        # Sort by concatenated_values_order then
        # Sort each group of products (0, 1, 2, ...) per attribute values
        # Sort each group of products by name,
        # if they have the same values or not values
        ordering = "-" if descending else ""
        return qs.order_by(
            f"{ordering}concatenated_values_order",
            f"{ordering}concatenated_values",
            f"{ordering}name",
        )


class Product(SeoModel, ModelWithMetadata, PublishableModel):
    product_type = models.ForeignKey(
        ProductType, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    description = models.TextField(blank=True)
    description_json = SanitizedJSONField(
        blank=True, default=dict, sanitizer=clean_draft_js
    )
    category = models.ForeignKey(
        Category,
        related_name="products",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    currency = models.CharField(
        max_length=settings.DEFAULT_CURRENCY_CODE_LENGTH,
        default=settings.DEFAULT_CURRENCY,
    )

    minimal_variant_price_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        blank=True,
        null=True,
    )
    minimal_variant_price = MoneyField(
        amount_field="minimal_variant_price_amount", currency_field="currency"
    )

saleor/templates/invoices/invoice.html
{% load i18n %}
{% load price from taxed_prices %}
<!DOCTYPE html>
<html>

<head>
    <style>
        @page {
            margin: 0.5cm;
            @bottom-right {
                content: counter(page) " of " counter(pages);
                font-size: 12px;
                letter-spacing: 0.02em;
                color: rgba(40, 35, 74, 0.6);
                margin: -15px 28px 40px 0;
            }
        }

        @font-face {
            font-family: Custom;
            font-style: normal;
            src: url({{ font_path }}) format('truetype');
        }

        body {
            font-family: Custom;
        }

        .section-header,
        .section-invoice-info {
            background-color: #EFF5F8;
            height: 255px;
        }

        .section-left {
            width: 50%;
            float: left;
        }

        .section-right {
            width: 50%;
            float: right;
        }

        .header-category {
            font-size: 14px;
            letter-spacing: 0.05em;
            color: rgba(40, 35, 74, 0.6);
            line-height: 1.8;
        }

        .header-category-small {
            font-size: 11px;
            letter-spacing: 0.05em;
            color: rgba(40, 35, 74, 0.6);
            line-height: 1.8;
        }

        .header-item {
            font-weight: bold;
            font-size: 14px;
            color: #28234A;
            display: block;
            padding-bottom: 5px;
            font-family: Inter;
            letter-spacing: 0.05em;
            line-height: 13px;
        }

        .header-title {
            display: block;
            padding-bottom: 5px;
            font-family: Inter;
            letter-spacing: -0.02em;
            font-style: normal;
            font-weight: 600;
            font-size: 14px;
            line-height: 13px;
            color: #28234A;
        }

        .content-padded {
            padding: 27px;
        }

        .content-tight-padded {
            padding: 0 27px 0 27px;
        }

        .padded-top {
            padding-top: 30px;
        }

        .normal-text {
            font-size: 15px;
            color: #534f6e;
            line-height: 143.52%;
        }

        .normal-text-table {
            font-size: 15px;
            color: #28234A;
            line-height: 143.52%;
        }

        .summary-row {
            line-height: normal;
        }

        .padded-font {
            margin-top: 10px;
        }

        .padded-font-sm {
            margin-top: 3px;
        }

        .padded-font {
            margin-top: 1px;
        }

        .products-table {
            width: 100%;
            line-height: 1.4;
        }

        .summary-table {
            width: 100%;
            line-height: 1.8;
            padding-top: 20px;
        }

        .row-category > td,
        .row-product > td {
            padding: 7px 0 7px 0;
            border-bottom: 2px solid #CEE3ED;
        }

        .cell-product {
            width: 50%;
        }

        .cell-price {
            width: 20%;
            text-align: right;
        }

        .cell-price-content {
            padding-right: 57px;
        }

        .cell-quantity {
            width: 15%;
            text-align: right;
        }

        .cell-quantity-content {
            padding-right: 35px;
        }

        .cell-total-price {
            width: 15%;
            text-align: right;
        }

        .cell-summary {
            width: 80%;
            text-align: right;
            padding-right: 30px;
        }

        .content-separator {
            display: inline-block;
            width: 100%;
            border-bottom: 2px solid #CEE3ED;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <div class="section-header section-left">
        <div class="content-padded">
            <span class="normal-text">{{ order.billing_address.company_name }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.street_address_1 }}</span>
            <br />
            {% if order.billing_address.street_address_2 %}
                <span class="normal-text">{{ order.billing_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.billing_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.postal_code }}</span>
            <br />
            {% if order.billing_address.phone %}
                <span class="normal-text">{{ order.billing_address.phone }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.get_customer_email }}</span>
            <br />
        </div>
    </div>
    <div class="section-invoice-info section-right">
        <div class="content-padded">
            <span class="header-title">
                {% trans "INVOICE INFORMATION" context "Invoice PDF header" %}
            </span>
            <span class="header-category">
                {% trans "Invoice number:" context "Invoice PDF header: Invoice number" %}
            </span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ invoice.number }}</span>
            <div class="padded-font"></div>
            <span class="header-category">
                {% trans "Order:" context "Invoice PDF header: order number" %}
            </span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ order.id }}</span>
            <div class="padded-font"></div>
            <span class="header-category">
                {% trans "Date:" context "Invoice PDF header" %}
            </span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ creation_date }}</span>
            <div class="padded-font"></div>
            <span class="header-category">
                {% trans "Amount:" context "Invoice PDF amount (price)" %}
            </span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{% price order.total_gross %}</span>
        </div>
    </div>
    <div class="section-left">
        <div class="content-tight-padded padded-top">
            <span class="header-title">
                {% trans "BILLING ADDRESS" context "Invoice PDF" %}
            </span>
            <br />
            <span class="normal-text">
                {{ order.billing_address.first_name }}
                {{ order.billing_address.last_name }}
            </span>
            <br />
            <span class="normal-text">{{ order.billing_address.street_address_1 }}</span>
            <br />
            {% if order.billing_address.street_address_2 %}
                <span class="normal-text">{{ order.billing_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.billing_address.country }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.postal_code }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.phone }}</span>
            <br />
            <span class="normal-text">{{ order.get_customer_email }}</span>
            <br />
        </div>
    </div>
    <div class="section-right">
        <div class="content-tight-padded padded-top">
            <span class="header-title">
                {% trans "SHIPMENT ADDRESS" context "Invoice PDF" %}
            </span>
            <br />
            <span class="normal-text">
                {{ order.shipping_address.first_name }}
                {{ order.shipping_address.last_name }}
            </span>
            <br />
            <span class="normal-text">{{ order.shipping_address.street_address_1 }}</span>
            <br />
            {% if order.shipping_address.street_address_2 %}
                <span class="normal-text">{{ order.shipping_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.shipping_address.country }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.postal_code }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.phone }}</span>
            <br />
            <span class="normal-text">{{ order.user_email }}</span>
            <br />
        </div>
    </div>
    <div class="content-tight-padded">
        <div class="content-separator">&nbsp;</div>
    </div>
    <div class="section-left">
        <div class="content-tight-padded padded-top">
            <span class="header-title">{% trans "PAYMENT METHOD" context "Invoice PDF" %}</span>
            <br />
            {% if order.get_last_payment %}
                <span class="normal-text">{{ order.get_last_payment.gateway }}</span>
            {% else %}
                <span class="normal-text">
                    {% trans "Unpaid" context "Invoice PDF: Payment method value" %}
                </span>
            {% endif %}
            <br />
        </div>
    </div>
    <div class="section-right">
        <div class="content-tight-padded padded-top">
            <span class="header-title">{% trans "SHIPMENT METHOD" context "Invoice PDF" %}</span>
            <br />
            <span class="normal-text">{{ order.shipping_method_name }}</span>
            <br />
        </div>
    </div>
    <div class="content-tight-padded">
        <div class="content-separator">&nbsp;</div>
    </div>
    <div class="content-padded">
        <span class="header-title">{% trans "ITEMS ORDERED" context "Invoice PDF table header" %}</span>
        {% include "invoices/invoice_products_table.html" with products=products_first_page %}
        {% if not rest_of_products|length %}
            {% if products_first_page|length == 4 %}
                <div class="page-break"></div>
            {% endif %}
            {% include "invoices/invoice_summary_table.html" with order=order %}
        {% else %}
            {% for product_set in rest_of_products %}
                <div class="page-break"></div>
                {% include "invoices/invoice_products_table.html" with products=product_set %}
                {% if forloop.last %}
                    {% if product_set|length > 11 %}
                        <div class="page-break"></div>
                    {% endif %}
                    {% include "invoices/invoice_summary_table.html" with order=order %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</body>

</html>

saleor/templates/invoices/invoice_products_table.html
{% load i18n %}
{% load price from taxed_prices %}
<table class="products-table">
    <tbody>
        <tr class="row-category">
            <td class="cell-product">
                <span class="header-category-small">{% trans "Products" context "Invoice PDF table" %}</span>
            </td>
            <td class="cell-price">
                <span class="header-category-small cell-price-content">{% trans "Price" context "Invoice PDF table" %}</span>
            </td>
            <td class="cell-quantity">
                <span class="header-category-small cell-quantity-content">{% trans "Quantity" context "Invoice PDF table" %}</span>
            </td>
            <td class="cell-total-price">
                <span class="header-category-small">{% trans "Total Price" context "Invoice PDF table" %}</span>
            </td>
        </tr>
        {% for product in products %}
        <tr class="row-product">
            <td class="cell-product">
                <span class="normal-text-table">
                    {{ product|truncatechars:46 }}
                    <div class="padded-font-small"></div>
                    <span class="header-category-small">SKU: {{ product.product_sku }}</span>
                </span>
            </td>
            <td class="cell-price">
                <span class="normal-text-table cell-price-content">{% price product.unit_price.gross %}</span>
            </td>
            <td class="cell-quantity">
                <span class="normal-text-table cell-quantity-content">{{ product.quantity }}</span>
            </td>
            <td class="cell-total-price">
                <span class="normal-text-table">{% price product.get_total.gross %}</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

saleor/templates/invoices/invoice_summary_table.html
{% load i18n %}
{% load price from taxed_prices %}
<table class="summary-table">
    <tbody>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">
                    {% trans "Subtotal" context "Invoice PDF summary" %}
                </span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.get_subtotal.gross %}
                </span>
            </td>
        </tr>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">
                    {% trans "Delivery Cost" context "Invoice PDF summary" %}
                </span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.shipping_price.gross %}
                </span>
            </td>
        </tr>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">
                    {% trans "Tax" context "Invoice PDF summary" %}
                </span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.total.tax %}
                </span>
            </td>
        </tr>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">
                    <b>{% trans "Grand Total" context "Invoice PDF summary" %}</b>
                </span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.total.gross %}
                </span>
            </td>
        </tr>
    </tbody>
</table>